import Head from 'next/head'
import Images from '@/components/Images'
import { useState } from "react";
import Predictions from '@/components/Predictions'



export default function App() {
  const [navbarOpen, setNavbarOpen] = useState(false);
  const [openTab, setOpenTab] = useState(1);

  return (
    <>

      <Head>
        <title>Data Annotation Tool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="relative flex flex-wrap items-center justify-between px-2 py-3 bg-blue-500 mb-3">
        <div className="container px-4 mx-auto flex flex-wrap items-center justify-between">
          <div className="w-full relative flex justify-between lg:w-auto lg:static lg:block lg:justify-start">
            <a
              className="text-sm font-bold leading-relaxed inline-block mr-4 py-2 whitespace-nowrap uppercase text-white"
              href="#pablo"
            >
              Data Annotation Tool
            </a>
            <button
              className="text-white cursor-pointer text-xl leading-none px-3 py-1 border border-solid border-transparent rounded bg-transparent block lg:hidden outline-none focus:outline-none"
              type="button"
              onClick={() => setNavbarOpen(!navbarOpen)}
            >
              <i className="fas fa-bars"></i>
            </button>
          </div>
          <div
            className={
              "lg:flex flex-grow items-center" +
              (navbarOpen ? " flex" : " hidden")
            }
            id="example-navbar-danger"
          >
          
          </div>
        </div>
      </nav>
      <div className="container px-5 py-24 mx-auto flex-row">
                    <ul className="mr-2 flex">
                        <li>
                            <a
                                href="#" 
                                onClick={() => setOpenTab(1)}
                                className={` ${openTab === 1 ? "text-white-500 border-yellow-500" : ""} text-gray-600 py-4 px-6 block hover:text-blue-500 focus:outline-none text-blue-500 border-b-2 font-medium border-blue-500 flex-row`}
                            >
                               Images 
                            </a>
                        </li>
                        <li>
                            <a
                                href="#"
                                onClick={() => setOpenTab(2)}
                                className={` ${openTab === 2 ? "text-white-500" : ""} text-gray-600 py-4 px-6 block hover:text-blue-500 focus:outline-none text-blue-500 border-b-2 font-medium border-blue-500`}


                            >
                                Predictions
                            </a>
                        </li>
                   </ul>
                    <div className="p-0 mt-3 ">
                        <div className={openTab === 1 ? "block" : "hidden"}>
                            <Images />
                        </div>
                        <div className={openTab === 2 ? "block" : "hidden"}>
                            <Predictions />
                        </div>
                   </div>
                </div>

            
    </>
  )
}
